// <auto-generated />
using System;
using Lantrn.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lantrn.Infra.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260923074548_AddDocuments")]
    partial class AddDocuments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Lantrn.Infra.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Collection")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Markdown")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Collection", "Source")
                        .IsUnique();

                    b.ToTable("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
