// <auto-generated />
using System;
using Lantrn.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lantrn.Infra.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260923080744_AddCollectionsAndTags")]
    partial class AddCollectionsAndTags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Lantrn.Infra.Collection", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("Lantrn.Infra.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Collection")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Markdown")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Collection", "Source")
                        .IsUnique();

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Lantrn.Infra.DocumentTag", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("DocumentId", "Name");

                    b.HasIndex("Name");

                    b.ToTable("DocumentTag");
                });

            modelBuilder.Entity("Lantrn.Infra.Document", b =>
                {
                    b.HasOne("Lantrn.Infra.Collection", null)
                        .WithMany("Documents")
                        .HasForeignKey("Collection")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lantrn.Infra.DocumentTag", b =>
                {
                    b.HasOne("Lantrn.Infra.Document", null)
                        .WithMany("Tags")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lantrn.Infra.Collection", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Lantrn.Infra.Document", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
